name: deploy to tencent
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # yarn install
      - name: yarn install
        run: |
          yarn
        env:
          CI: true
      - name: gatsby build
        uses: jzweifel/gatsby-cli-github-action@master
      # Deploy
      - name: Deploy tencent
        uses: easingthemes/ssh-deploy@v2.0.9
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: "root"
          TARGET: ${{ secrets.TARGET }}
